// scripts/seed-exams.ts
import { db } from "@/lib/db";

async function seedExams() {
  await db.exam.createMany({
    data: [
      // ======= GLICOSE =======
      {
        name: "GLICEMIA DE JEJUM",
        group: "Todos",
        normal_min: 70,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 125,
        hard_value: 126,
        unit: "mg/dL",
      },
      {
        name: "HEMOGLOBINA GLICADA (HbA1c)",
        group: "Todos",
        normal_min: 4.0,
        normal_max: 5.6,
        intermediary_min: 5.7,
        intermediary_max: 6.4,
        hard_value: 6.5,
        unit: "%",
      },
      {
        name: "GLICOSE PÓS-PRANDIAL (2h após refeição)",
        group: "Todos",
        normal_min: 70,
        normal_max: 139,
        intermediary_min: 140,
        intermediary_max: 199,
        hard_value: 200,
        unit: "mg/dL",
      },

      // ======= PERFIL LIPÍDICO =======
      {
        name: "COLESTEROL TOTAL",
        group: "Todos",
        normal_min: 0,
        normal_max: 199,
        intermediary_min: 200,
        intermediary_max: 239,
        hard_value: 240,
        unit: "mg/dL",
      },
      {
        name: "LDL COLESTEROL",
        group: "Todos",
        normal_min: 0,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 129,
        hard_value: 130,
        unit: "mg/dL",
      },
      {
        name: "HDL COLESTEROL",
        group: "Homens adultos (18–59)",
        normal_min: 40,
        normal_max: 1000,
        intermediary_min: 35,
        intermediary_max: 39,
        hard_value: 34,
        unit: "mg/dL",
      },
      {
        name: "HDL COLESTEROL",
        group: "Mulheres adultas (18–59)",
        normal_min: 50,
        normal_max: 1000,
        intermediary_min: 45,
        intermediary_max: 49,
        hard_value: 44,
        unit: "mg/dL",
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Homens adultos (18–59)",
        normal_min: 0,
        normal_max: 149,
        intermediary_min: 150,
        intermediary_max: 199,
        hard_value: 200,
        unit: "mg/dL",
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Crianças (<10 anos)",
        normal_min: 0,
        normal_max: 75,
        intermediary_min: 76,
        intermediary_max: 99,
        hard_value: 100,
        unit: "mg/dL",
      },

      // ======= FUNÇÃO HEPÁTICA =======
      {
        name: "TGO (AST)",
        group: "Todos",
        normal_min: 10,
        normal_max: 40,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 41,
        unit: "U/L",
      },
      {
        name: "TGP (ALT)",
        group: "Todos",
        normal_min: 10,
        normal_max: 45,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 46,
        unit: "U/L",
      },
      {
        name: "GAMA GT (GGT)",
        group: "Homens adultos (18–59)",
        normal_min: 10,
        normal_max: 55,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 56,
        unit: "U/L",
      },
      {
        name: "GAMA GT (GGT)",
        group: "Mulheres adultas (18–59)",
        normal_min: 7,
        normal_max: 32,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 33,
        unit: "U/L",
      },
      {
        name: "FOSFATASE ALCALINA",
        group: "Todos",
        normal_min: 30,
        normal_max: 120,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 121,
        unit: "U/L",
      },

      // ======= FUNÇÃO RENAL =======
      {
        name: "CREATININA",
        group: "Homens adultos (18–59)",
        normal_min: 0.7,
        normal_max: 1.3,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1.4,
        unit: "mg/dL",
      },
      {
        name: "CREATININA",
        group: "Mulheres adultas (18–59)",
        normal_min: 0.6,
        normal_max: 1.1,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1.2,
        unit: "mg/dL",
      },
      {
        name: "UREIA",
        group: "Todos",
        normal_min: 15,
        normal_max: 45,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 46,
        unit: "mg/dL",
      },
      {
        name: "MICROALBUMINÚRIA",
        group: "Todos",
        normal_min: 0,
        normal_max: 29,
        intermediary_min: 30,
        intermediary_max: 300,
        hard_value: 301,
        unit: "mg/g creatinina",
      },

      // ======= HORMONAIS / METABÓLICOS =======
      {
        name: "INSULINA JEJUM",
        group: "Todos",
        normal_min: 2.0,
        normal_max: 25.0,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 25.1,
        unit: "µIU/mL",
      },
      {
        name: "TSH",
        group: "Todos",
        normal_min: 0.4,
        normal_max: 4.5,
        intermediary_min: 4.6,
        intermediary_max: 10.0,
        hard_value: 10.1,
        unit: "µIU/mL",
      },
      {
        name: "T4 LIVRE",
        group: "Todos",
        normal_min: 0.8,
        normal_max: 1.8,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1.9,
        unit: "ng/dL",
      },
      {
        name: "TESTOSTERONA TOTAL",
        group: "Homens adultos (18–59)",
        normal_min: 300,
        normal_max: 1000,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1001,
        unit: "ng/dL",
      },
      {
        name: "TESTOSTERONA TOTAL",
        group: "Mulheres adultas (18–59)",
        normal_min: 15,
        normal_max: 70,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 71,
        unit: "ng/dL",
      },
      {
        name: "17-HIDROXIPROGESTERONA",
        group: "Todos",
        normal_min: 0.2,
        normal_max: 1.3,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1.4,
        unit: "ng/mL",
      },
      {
        name: "PROGESTERONA",
        group: "Mulheres adultas (18–59)",
        normal_min: 0.1,
        normal_max: 0.8,
        intermediary_min: 0.9,
        intermediary_max: 20,
        hard_value: 21,
        unit: "ng/mL",
      },
      {
        name: "PROGESTERONA",
        group: "Homens adultos (18–59)",
        normal_min: 0.1,
        normal_max: 1,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1.1,
        unit: "ng/mL",
      },
      {
        name: "ESTRADIOL (E2)",
        group: "Mulheres adultas (18–59)",
        normal_min: 30,
        normal_max: 400,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 401,
        unit: "pg/mL",
      },
      {
        name: "ESTRADIOL (E2)",
        group: "Homens adultos (18–59)",
        normal_min: 10,
        normal_max: 50,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 51,
        unit: "pg/mL",
      },
      {
        name: "SHBG",
        group: "Todos",
        normal_min: 18,
        normal_max: 144,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 145,
        unit: "nmol/L",
      },
      {
        name: "DHEA-S",
        group: "Homens adultos (18–59)",
        normal_min: 180,
        normal_max: 1250,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 1251,
        unit: "µg/dL",
      },
      {
        name: "DHEA-S",
        group: "Mulheres adultas (18–59)",
        normal_min: 35,
        normal_max: 430,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 431,
        unit: "µg/dL",
      },
    ],
  });

  console.log("✅ Todos os exames foram inseridos com sucesso.");
}

seedExams()
  .catch((e) => {
    console.error("❌ Erro ao inserir exames:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  }); 