// scripts/seed-exams.ts
import { db } from "@/lib/db";

async function seedExams() {
  await db.exam.createMany({
    data: [
      {
        name: "GLICEMIA",
        group: "Homens adultos (18–59)",
        normal_min: 70,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 125,
        hard_value: 126,
      },
      {
        name: "GLICEMIA",
        group: "Mulheres adultas (18–59)",
        normal_min: 70,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 125,
        hard_value: 126,
      },
      {
        name: "GLICEMIA",
        group: "Idosos (≥ 60 anos)",
        normal_min: 70,
        normal_max: 105,
        intermediary_min: 106,
        intermediary_max: 125,
        hard_value: 126,
      },
      {
        name: "GLICEMIA",
        group: "Crianças (>10 anos)",
        normal_min: 70,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 125,
        hard_value: 126,
      },
      {
        name: "GLICEMIA",
        group: "Crianças (<10 anos)",
        normal_min: 65,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 125,
        hard_value: 126,
      },
      {
        name: "HEMOGLOBINA GLICADA (HbA1c)",
        group: "Todos",
        normal_min: 4.0,
        normal_max: 5.6,
        intermediary_min: 5.7,
        intermediary_max: 6.4,
        hard_value: 6.5,
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Homens adultos (18–59)",
        normal_min: 0,
        normal_max: 149,
        intermediary_min: 150,
        intermediary_max: 199,
        hard_value: 200,
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Mulheres adultas (18–59)",
        normal_min: 0,
        normal_max: 149,
        intermediary_min: 150,
        intermediary_max: 199,
        hard_value: 200,
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Idosos (≥ 60 anos)",
        normal_min: 0,
        normal_max: 149,
        intermediary_min: 150,
        intermediary_max: 199,
        hard_value: 200,
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Crianças (>10 anos)",
        normal_min: 0,
        normal_max: 90,
        intermediary_min: 91,
        intermediary_max: 129,
        hard_value: 130,
      },
      {
        name: "TRIGLICERÍDEOS",
        group: "Crianças (<10 anos)",
        normal_min: 0,
        normal_max: 75,
        intermediary_min: 76,
        intermediary_max: 99,
        hard_value: 100,
      },
      {
        name: "HDL COLESTEROL",
        group: "Homens adultos (18–59)",
        normal_min: 40,
        normal_max: 1000,
        intermediary_min: 35,
        intermediary_max: 39,
        hard_value: 34,
      },
      {
        name: "HDL COLESTEROL",
        group: "Mulheres adultas (18–59)",
        normal_min: 50,
        normal_max: 1000,
        intermediary_min: 45,
        intermediary_max: 49,
        hard_value: 44,
      },
      {
        name: "HDL COLESTEROL",
        group: "Crianças (>10 anos)",
        normal_min: 45,
        normal_max: 1000,
        intermediary_min: 40,
        intermediary_max: 44,
        hard_value: 39,
      },
      {
        name: "HDL COLESTEROL",
        group: "Crianças (<10 anos)",
        normal_min: 45,
        normal_max: 1000,
        intermediary_min: 40,
        intermediary_max: 44,
        hard_value: 39,
      },
      {
        name: "LDL COLESTEROL",
        group: "Todos",
        normal_min: 0,
        normal_max: 99,
        intermediary_min: 100,
        intermediary_max: 129,
        hard_value: 130,
      },
      {
        name: "COLESTEROL TOTAL",
        group: "Todos",
        normal_min: 0,
        normal_max: 199,
        intermediary_min: 200,
        intermediary_max: 239,
        hard_value: 240,
      },
      {
        name: "TGO (AST)",
        group: "Homens adultos (18–59)",
        normal_min: 10,
        normal_max: 40,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 41,
      },
      {
        name: "TGP (ALT)",
        group: "Homens adultos (18–59)",
        normal_min: 10,
        normal_max: 45,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 46,
      },
      {
        name: "TSH",
        group: "Todos",
        normal_min: 0.4,
        normal_max: 4.5,
        intermediary_min: 4.6,
        intermediary_max: 10.0,
        hard_value: 10.1,
      },
      {
        name: "INSULINA JEJUM",
        group: "Todos",
        normal_min: 2.0,
        normal_max: 25.0,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 25.1,
      },
      {
        name: "ÁCIDO ÚRICO",
        group: "Homens adultos (18–59)",
        normal_min: 3.5,
        normal_max: 7.0,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 7.1,
      },
      {
        name: "ÁCIDO ÚRICO",
        group: "Mulheres adultas (18–59)",
        normal_min: 2.5,
        normal_max: 6.0,
        intermediary_min: null,
        intermediary_max: null,
        hard_value: 6.1,
      },
      {
        name: "PCR ULTRASSENSÍVEL",
        group: "Todos",
        normal_min: 0.0,
        normal_max: 1.0,
        intermediary_min: 1.1,
        intermediary_max: 3.0,
        hard_value: 3.1,
      }
    ]
  });

  console.log("Exames inseridos com sucesso.");
}

seedExams()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    db.$disconnect();
  });
